[#chapter-algo-sort]
= ソート

== 内部ソート

=== 挿入ソート

ソート対象レコードはINPUT+1からINPUT+Nまでの領域に格納してある。
rI1 = j-N, rI2 = i, rA = R = k とする。

.プログラムS
----
01 START ENT1 2-N           1
02 2H    LDA  INPUT+N,1     N-1
03       ENT2 N-1,1         N-1
04 3H    CMPA INPUT,2       B+N-1-A
05       JGE  5F            B+N-1-A
06 4H    LDX  INPUT,2       B
07       STX  INPUT+1,2     B
08       DEC2 1             B
09       J2P  3B            B
10 5H    STA  INPUT+1,2     N-1
11       INC1 1             N-1
12       J1NP 2B            N-1
----

* N: ファイルのサイズ
* A: ステップ4でiを0まで引く回数
* B: 移動の回数

Bは順列 stem:[K_1, \dots, K_N] に含まれる逆転の合計である。
プログラムの実行時間で支配的なのはこの stem:[B] である。

=== シェルソート

シェルソートで使う増分数列 stem:[h_{t-1}, \dots, h_{0}] で優れたものを選びたい。

== 増加部分列

=== Erdős-Szekeres の定理

* Ref
** https://en.wikipedia.org/wiki/Erd%C5%91s%E2%80%93Szekeres_theorem[Wikipedia]
** http://www.numdam.org/item/CM_1935__2__463_0.pdf[A combinatorial problem in geometry]
** http://www-stat.wharton.upenn.edu/~steele/Publications/PDF/VOTMSTOEAS.pdf[Variations on the monotone subsequence theme of Erdős and Szekeres]

Statement:: 
stem:[1, \dots, N] の整数の順列 stem:[a_1, \dots, a_N] の最長増加部分列の長さを stem:[I_N] 、
最長減少部分列の長さを stem:[D_N] とする。
stem:[Max(I_N, D_N) \ge \sqrt{N}] である。

Proof 1::
簡単のため、 stem:[N] は平方数と仮定する。
以下のような集合 stem:[K_i] stem:[(i=1, \dots, N)] を定義する。
stem:[K_i = \{k | a_k \test{で終わる最長の増加部分列の長さが} i\}]
背理法で証明する。
stem:[I_N < \sqrt{N}] と仮定する。
stem:[K_i] は以下の性質を持つ。
. stem:[1] から stem:[N] までの数はいずれかの stem:[K_i] に含まれる
. stem:[i\neq j] なら stem:[K_i \cap K_j = \phi]
. stem:[K_{\sqrt{N}}, K_{\sqrt{N}+1}, \dots = \phi] +
この時、stem:[K_1, \dots, K_{sqrt{N}-1}] のうち、
元の数が stem:[\sqrt{N}] 以上の集合が存在する。
この集合の元を集めると、
長さが stem:[\sqrt{N}] 以上の減少部分列が得られる。

Proof 2::
全ての stem:[a_i] を stem:[(i_i, d_i)] でラベル付けする。
stem:[i_i] は stem:[a_i] で終わる最長の増加部分列の長さ、
stem:[d_i] は stem:[a_i] で終わる最長の減少部分列の長さである。
全ての stem:[a_i] について、 #このラベルは一意# である。
stem:[i_i, d_i < \sqrt{N}] とすると、
ラベルの数は stem:[(\sqrt{N}-1)^2] 以下に対して、
数は stem:[N] 個存在する。
これはラベルの一意性に矛盾する。
