[#taocp-4A-5-2]
= 内部ソート

== 挿入ソート

ソート対象レコードはINPUT+1からINPUT+Nまでの領域に格納してある。
rI1 = j-N, rI2 = i, rA = R = k とする。

.プログラムS
----
01 START ENT1 2-N           1
02 2H    LDA  INPUT+N,1     N-1
03       ENT2 N-1,1         N-1
04 3H    CMPA INPUT,2       B+N-1-A
05       JGE  5F            B+N-1-A
06 4H    LDX  INPUT,2       B
07       STX  INPUT+1,2     B
08       DEC2 1             B
09       J2P  3B            B
10 5H    STA  INPUT+1,2     N-1
11       INC1 1             N-1
12       J1NP 2B            N-1
----

* N: ファイルのサイズ
* A: ステップ4でiを0まで引く回数
* B: 移動の回数

Bは順列 stem:[K_1, \dots, K_N] に含まれる逆転の合計である。
プログラムの実行時間で支配的なのはこの stem:[B] である。

== シェルソート

シェルソートで使う増分数列 stem:[h_{t-1}, \dots, h_{0}] で優れたものを選びたい。
部分列のソートを挿入ソートで行う場合、 stem:[B] の値が重要となる。
この値を評価する。

シェルソートのアルゴリズムで増分 stem:[h] で定義される部分列のソートを行う処理を stem:[h] ソートと呼ぶ。
シェルソートは stem:[h_{t-1}] ソート、 stem:[h_{t-2}] ソート、...、 stem:[h_{0}] ソートを行う構成となる。
また、 stem:[1\le i\le N-h] について stem:[K_i \le K_{i+h}] となっている数列を、 stem:[h] ソート済みと呼ぶ。

最も簡単な場合として、 stem:[h_1 = 2, h_0 = 1] の場合を考える。
2ソート済み数列は stem:[\binom{n}{\lfloor n/2 \rfloor}] 個存在し、全て等しい確率で生じる。
全ての2ソート済み数列の逆転の合計個数を stem:[A_n] とする。

<---------- stem:[A_n] を正方格子の A から B への道と関連付ける ---------->

よって、

[latexmath]
++++
A_n = \lfloor n/2 \rfloor 2^{n-2}
++++

となる。逆転数の平均値は次のように計算できる。

[latexmath]
++++
\lfloor n/2 \rfloow 2^{n-2} / \binom{n}{\lfloor n/2 \rfloor} \approx 0.15 n^{3/2}
++++

定理H::
  stem:[\{1, \dots, n\}] の stem:[h] ソート済み順列に含む逆転の平均は、
  stem:[1 = \lfloor n / h \rfloor] で stem:[r = n mod h] とすると、次のようになる。 +
  stem:[f(n, h) = \frac{2^{2q-1}q!q!}{(2q+1)!} (\binom{h}{2}q(q+1) + binom{r}{2} (q+1) - \frac{1}{2}\binom{h-r}{2}q)]
